version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: taskmanager_postgres
    restart: always
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: taskmanager_adminer
    restart: always
    ports:
      - "8081:8080"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8082:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json

#  app:
#    build: .
#    container_name: taskmanager_app
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskdb
#      SPRING_DATASOURCE_USERNAME: taskuser
#      SPRING_DATASOURCE_PASSWORD: taskpass
#    ports:
#      - "8080:8080"

volumes:
  postgres_data:
