apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-manager.fullname" . }}-secret
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.datasourcePassword | quote }}
  SPRING_FLYWAY_PASSWORD: {{ .Values.secrets.flywayPassword | quote }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.secrets.keycloakClientSecret | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
