name: OWASP ZAP Security Scan

on:
  workflow_dispatch:  # Manually triggered
permissions:
  contents: read
  issues: write  

jobs:
  zap-base-scan:
    name: OWASP ZAP Baseline Scan
    runs-on: ubuntu-latest
    steps:
      - name: Run ZAP baseline scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://www.ppt.doctorbox.de'
          fail_action: false
          allow_issue_writing: false
          rules_file_name: '.zap/rules.tsv'
          artifact_name: zap-base-scan-report
          cmd_options: '-a'

  zap-full-scan:
    name: OWASP ZAP Full Scan
    runs-on: ubuntu-latest
    steps:
      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'https://www.ppt.doctorbox.de'
          fail_action: false
          allow_issue_writing: false
          rules_file_name: '.zap/rules.tsv'
          artifact_name: zap-full-scan-report
          cmd_options: '-a'
